In [1]:
import numpy as np
import cv2

In [12]:
img = cv2.imread('me.jpg')
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)   # 圖片轉灰階
#gray = cv2.medianBlur(gray, 5)                # 如果一直偵測到雜訊，可使用模糊的方式去除雜訊
face_cascade = cv2.CascadeClassifier("haarcascade_frontalface_default.xml")   # 載入人臉模型
eye_cascade = cv2.CascadeClassifier("haarcascade_eye.xml")  # 使用眼睛模型
eyes = eye_cascade.detectMultiScale(gray)  

# 偵測眼睛
for (x, y, w, h) in eyes:
    cv2.rectangle(img, (x, y), (x+w, y+h), (0, 255, 0), 2)      # 標記綠色方框
    crop_img = img[y:y+h, x:x+w]
    cv2.imshow("cropped", crop_img)
    cv2.waitKey(0)

eyes = eye_cascade.detectMultiScale(gray)      # 偵測眼睛
#     for (x, y, w, h) in eyes:
#         cv2.rectangle(img, (x, y), (x+w, y+h), (0, 255, 0), 2)

faces = face_cascade.detectMultiScale(gray)
true_eyes = np.zeros(shape=(0,0))
for (x, y, w, h) in faces:
    for(a,b,c,d) in eyes:
          if(a > x and a+c < x+w and b>y and b+d < w+h):
                cv2.rectangle(img, (a,b), (a+c,b+d),(0,255,0),2)
                true_eyes = np.append(true_eyes,np.array([a,b,c,d]))
eye = np.zeros(shape=(int(len(true_eyes)/4),4))

for i in range(int(len(true_eyes)/4)):
    eye[i] = true_eyes[i*4],true_eyes[i*4+1],true_eyes[i*4+2],true_eyes[i*4+3]
print(eye)
# for x,y,w,h in eye:
#   crop_img = img[ y:y+h,x:x+w]
#   cv2.imshow('sdad', crop_img)
cv2.imshow('oxxostudio', img)
cv2.waitKey(0)   # 按下任意鍵停止
cv2.destroyAllWindows()

[[366. 412. 102. 102.]
 [542. 586.  82.  82.]
 [606. 405. 115. 115.]]


In [3]:
import cv2
cap = cv2.VideoCapture(0)
eye_cascade = cv2.CascadeClassifier("haarcascade_eye.xml")          # 使用眼睛模型
# mouth_cascade = cv2.CascadeClassifier("haarcascade_mcs_mouth.xml")  # 使用嘴巴模型
# nose_cascade = cv2.CascadeClassifier("haarcascade_mcs_nose.xml")    # 使用鼻子模型

face_cascade = cv2.CascadeClassifier("haarcascade_frontalface_default.xml")   # 載入人臉模型

if not cap.isOpened():
    print("Cannot open camera")
    exit()
while True:
    ret, frame = cap.read()
    if not ret:
        print("Cannot receive frame")
        break
    img = cv2.resize(frame,(600,320))
    gray = cv2.medianBlur(img, 1)
    gray = cv2.cvtColor(gray, cv2.COLOR_BGR2GRAY)
    gray = cv2.medianBlur(gray, 5)

    eyes = eye_cascade.detectMultiScale(gray)      # 偵測眼睛
#     for (x, y, w, h) in eyes:
#         cv2.rectangle(img, (x, y), (x+w, y+h), (0, 255, 0), 2)
        
    faces = face_cascade.detectMultiScale(gray)
    for (x, y, w, h) in faces:
        for(a,b,c,d) in eyes:
              if(a > x and a+c < x+w and b>y and b+d < w+h):
                    cv2.rectangle(img, (a,b), (a+c,b+d),(0,255,0),2)
#     mouths = mouth_cascade.detectMultiScale(gray)  # 偵測嘴巴
#     for (x, y, w, h) in mouths:
#         cv2.rectangle(img, (x, y), (x+w, y+h), (0, 0, 255), 2)

#     noses = nose_cascade.detectMultiScale(gray)    # 偵測鼻子
#     for (x, y, w, h) in noses:
#         cv2.rectangle(img, (x, y), (x+w, y+h), (255, 0, 0), 2)

    cv2.imshow('oxxostudio', img)
    if cv2.waitKey(1) == ord('q'):
        break     # 按下 q 鍵停止
cap.release()
cv2.destroyAllWindows()

In [5]:
import cv2
img = cv2.imread('me.jpg')
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
left_eye = cv2.CascadeClassifier("haarcascade_lefteye_2splits.xml")
eye = left_eye.detectMultiScale(gray)
for (x, y, w, h) in eyes:
    cv2.rectangle(img, (x, y), (x+w, y+h), (0, 255, 0), 2)
cv2.imshow('oxxostudio', img)
cv2.waitKey(0)   # 按下任意鍵停止
cv2.destroyAllWindows()

In [5]:
import tensorflow as tf
import cv2
import numpy as np
#model = tf.keras.models.load_model("./drowiness_new6.h5")   #load your model
face_cascade = cv2.CascadeClassifier("haarcascade_frontalface_default.xml")
eye_cascade = cv2.CascadeClassifier("haarcascade_eye.xml")


IMG_SIZE = 145
def prepare_camera(img_array):
    img_array = img_array / 255
    resized_array = cv2.resize(img_array, (IMG_SIZE, IMG_SIZE))
    return resized_array.reshape(-1, IMG_SIZE, IMG_SIZE, 3)

def cut_eyes(frame):
    faces = face_cascade.detectMultiScale(gray)
    eyes = eye_cascade.detectMultiScale(gray)
    true_eyes = np.zeros(shape=(0,0))
    for (x, y, w, h) in faces:
        for(a,b,c,d) in eyes:
              if(a > x and a+c < x+w and b>y and b+d < w+h):
                    cv2.rectangle(frame, (a,b), (a+c,b+d),(0,255,0),2)
                    true_eyes = np.append(true_eyes,np.array([a,b,c,d]))
    eye = np.zeros(shape=(int(len(true_eyes)/4),4))
    for i in range(int(len(true_eyes)/4)):
        eye[i] = true_eyes[i*4],true_eyes[i*4+1],true_eyes[i*4+2],true_eyes[i*4+3]
    return eye
cap = cv2.VideoCapture(0)


if not cap.isOpened():
    print("Cannot open camera")
    exit()
while True:
    ret, frame = cap.read()
    if not ret:
        print("Cannot receive frame")
        break
        
        
    frame = cv2.resize(frame,(540,320))              # 縮小尺寸，避免尺寸過大導致效能不好
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)   # 將鏡頭影像轉換成灰階
    faces = face_cascade.detectMultiScale(gray)      # 偵測人臉
    eyes = cut_eyes(gray)
    
    print(eyes)
    if(len(eyes) != 0):
        for x,y,w,h in eyes:
            crop_eye = frame[int(y):int(y+h), int(x):int(x+w)]
            cv2.imshow('sdas', crop_eye)
    if cv2.waitKey(1) == ord('q'):
        break        
    
#     for (x, y, w, h) in faces:
#         cv2.rectangle(frame, (x, y), (x+w, y+h), (0, 255, 0), 2)   # 標記人臉
        # prediction = model.predict(prepare_camera(frame))
        # prediction = model.predict(prepare("./train/yawn/18.jpg"))
        #label_out = str(np.argmax(prediction))
        #cv2.putText(frame, label_out, (x-10, y-10), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 255, 255), 1, cv2.LINE_AA)
#     cv2.imshow('oxxostudio', frame)
#     if cv2.waitKey(1) == ord('q'):
#         break
    
cap.release()
cv2.destroyAllWindows()

Cannot receive frame


In [ ]:
import tensorflow as tf
import cv2
import numpy as np
model = tf.keras.models.load_model("./drowiness_new6.h5")   #load your model
model_eye = tf.keras.models.load_model("./drowiness_new6_eye.h5")   #load your model

face_cascade = cv2.CascadeClassifier("haarcascade_frontalface_default.xml")
eye_cascade = cv2.CascadeClassifier("haarcascade_eye.xml")


IMG_SIZE = 145
def prepare_camera(img_array):
    img_array = img_array / 255
    resized_array = cv2.resize(img_array, (IMG_SIZE, IMG_SIZE))
    return resized_array.reshape(-1, IMG_SIZE, IMG_SIZE, 3)

def cut_eyes(frame):
    faces = face_cascade.detectMultiScale(gray)
    eyes = eye_cascade.detectMultiScale(gray)
    true_eyes = np.zeros(shape=(0,0))
    for (x, y, w, h) in faces:
        for(a,b,c,d) in eyes:
              if(a > x and a+c < x+w and b>y and b+d < w+h):
                    cv2.rectangle(frame, (a,b), (a+c,b+d),(0,255,0),2)
                    true_eyes = np.append(true_eyes,np.array([a,b,c,d]))
    eye = np.zeros(shape=(int(len(true_eyes)/4),4))
    for i in range(int(len(true_eyes)/4)):
        eye[i] = true_eyes[i*4],true_eyes[i*4+1],true_eyes[i*4+2],true_eyes[i*4+3]
    return eye
cap = cv2.VideoCapture(0)


if not cap.isOpened():
    print("Cannot open camera")
    exit()
while True:
    ret, frame = cap.read()
    if not ret:
        print("Cannot receive frame")
        break
        
        
    frame = cv2.resize(frame,(540,320))              # 縮小尺寸，避免尺寸過大導致效能不好
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)   # 將鏡頭影像轉換成灰階
    faces = face_cascade.detectMultiScale(gray)      # 偵測人臉
    eyes = cut_eyes(gray)
    
         
    
    for (x, y, w, h) in faces:
        cv2.rectangle(frame, (x, y), (x+w, y+h), (0, 255, 0), 2)   # 標記人臉
        crop_face = frame[int(y):int(y+h), int(x):int(x+w)]
        prediction = model.predict(prepare_camera(crop_face))
        crop_eye = None
        for _x,_y,_w,_h in eyes:
            crop_eye = frame[int(_y):int(_y+_h), int(_x):int(_x+_w)]
        if (len(eyes) != 0):
            prediction_eye = model_eye.predict(prepare_camera(crop_eye))
            label_eye = str(np.argmax(prediction_eye))
            cv2.putText(frame, label_eye, (x+20, y-10), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 255, 255), 1, cv2.LINE_AA)


        # prediction = model.predict(prepare("./train/yawn/18.jpg"))
        label_out = str(np.argmax(prediction))
        
        cv2.putText(frame, label_out, (x-10, y-10), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 255, 255), 1, cv2.LINE_AA)

    cv2.imshow('oxxostudio', frame)
    # for (x, y, w, h) in faces:
    #     crop_face = frame[int(y):int(y+h), int(x):int(x+w)]
    #     cv2.imshow('sdas', crop_face)
    if cv2.waitKey(1) == ord('q'):
        break
    
cap.release()
cv2.destroyAllWindows()

In [1]:
import tensorflow as tf
import cv2
import numpy as np

import dlib


#model = tf.keras.models.load_model("./drowiness_new6.h5")   #load your model
#model_eye = tf.keras.models.load_model("./drowiness_new6_eye.h5")   #load your model

# face_cascade = cv2.CascadeClassifier("haarcascade_frontalface_alt2.xml")
eye_cascade = cv2.CascadeClassifier("haarcascade_eye.xml")


IMG_SIZE = 145
def prepare_camera(img_array):
    img_array = img_array / 255
    resized_array = cv2.resize(img_array, (IMG_SIZE, IMG_SIZE))
    return resized_array.reshape(-1, IMG_SIZE, IMG_SIZE, 3)

def cut_eyes(frame):
    faces = face_cascade.detectMultiScale(gray)
    eyes = eye_cascade.detectMultiScale(gray)
    true_eyes = np.zeros(shape=(0,0))
    for (x, y, w, h) in faces:
        for(a,b,c,d) in eyes:
              if(a > x and a+c < x+w and b>y and b+d < w+h):
                    cv2.rectangle(frame, (a,b), (a+c,b+d),(0,255,0),2)
                    true_eyes = np.append(true_eyes,np.array([a,b,c,d]))
    eye = np.zeros(shape=(int(len(true_eyes)/4),4))
    for i in range(int(len(true_eyes)/4)):
        eye[i] = true_eyes[i*4],true_eyes[i*4+1],true_eyes[i*4+2],true_eyes[i*4+3]
    return eye
cap = cv2.VideoCapture(0)


if not cap.isOpened():
    print("Cannot open camera")
    exit()
while True:
    ret, frame = cap.read()
    if not ret:
        print("Cannot receive frame")
        break

   
        
        
    frame = cv2.resize(frame,(540,320))              # 縮小尺寸，避免尺寸過大導致效能不好
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)   # 將鏡頭影像轉換成灰階
    # faces = face_cascade.detectMultiScale(gray)      # 偵測人臉
    eyes = cut_eyes(gray)
    detector = dlib.get_frontal_face_detector()
    predictor = dlib.shape_predictor( 'shape_predictor_68_face_landmarks.dat')
    face_rects, scores, idx = detector.run(frame, 0)
    for i, d in enumerate(face_rects):
      x1 = d.left()
      y1 = d.top()
      x2 = d.right()
      y2 = d.bottom()
    #print(eyes)
    # if(len(eyes) != 0):
    #     for x,y,w,h in eyes:
    #         crop_eye = frame[int(y):int(y+h), int(x):int(x+w)]
    #         cv2.imshow('sdas', crop_eye)
    # if cv2.waitKey(1) == ord('q'):
    #     break        
    
    
    cv2.rectangle(frame, (x1, y1), (x2, y2), (0, 255, 0), 2)   # 標記人臉
    crop_face = frame[int(y1):int(y2), int(x1):int(x2)]
    prediction = model.predict(prepare_camera(crop_face))
    crop_eye = None
    flag = 0
    if (len(eyes) != 0):
        for _x,_y,_w,_h in eyes:
            if (_y < y1 + (y2-y1)/2):
                flag = 1
                crop_eye = frame[int(_y):int(_y+_h), int(_x):int(_x+_w)]
                # cv2.rectangle(frame, (int(_x), int(_y)), (int(_x)+int(_w), int(_y)+int(_h)), (0, 255, 0), 2)


        if (flag):
            prediction_eye = model_eye.predict(prepare_camera(crop_eye))
            label_eye = str(np.argmax(prediction_eye))
            pred_eye = closed_label(label_eye)
            # print("eye:", label_eye)
            cv2.putText(frame, str(pred_eye), (x1+20, y1-10), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 255, 255), 1, cv2.LINE_AA)
        else:
            pred_eye = closed_label(0)
            cv2.putText(frame, str(pred_eye), (x1+20, y1-10), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 255, 255), 1, cv2.LINE_AA)


        # prediction = model.predict(prepare("./train/yawn/18.jpg"))
        label_out = str(np.argmax(prediction))
        # print("face", label_out)
        cv2.putText(frame, label_out, (x-10, y-10), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 255, 255), 1, cv2.LINE_AA)

    cv2.imshow('Team13', frame)
    # for (x, y, w, h) in faces:
    #     crop_face = frame[int(y):int(y+h), int(x):int(x+w)]
    #     cv2.imshow('sdas', crop_face)
    if cv2.waitKey(1) == ord('q'):
        break
    
cap.release()
cv2.destroyAllWindows()

ModuleNotFoundError: No module named 'dlib'

In [2]:
import cv2
cap = cv2.VideoCapture(0)
eye_cascade = cv2.CascadeClassifier("haarcascade_eye.xml")          # 使用眼睛模型
mouth_cascade = cv2.CascadeClassifier("haarcascade_mcs_mouth.xml")  # 使用嘴巴模型
#nose_cascade = cv2.CascadeClassifier("haarcascade_mcs_nose.xml")    # 使用鼻子模型
if not cap.isOpened():
    print("Cannot open camera")
    exit()
while True:
    ret, frame = cap.read()
    if not ret:
        print("Cannot receive frame")
        break
    img = cv2.resize(frame,(540,320))
    gray = cv2.medianBlur(img, 1)
    gray = cv2.cvtColor(gray, cv2.COLOR_BGR2GRAY)
    gray = cv2.medianBlur(gray, 5)

    eyes = eye_cascade.detectMultiScale(gray)      # 偵測眼睛
    for (x, y, w, h) in eyes:
        cv2.rectangle(img, (x, y), (x+w, y+h), (0, 255, 0), 2)

    mouths = mouth_cascade.detectMultiScale(gray)  # 偵測嘴巴
    for (x, y, w, h) in mouths:
        cv2.rectangle(img, (x, y), (x+w, y+h), (0, 0, 255), 2)

#     noses = nose_cascade.detectMultiScale(gray)    # 偵測鼻子
#     for (x, y, w, h) in noses:
#         cv2.rectangle(img, (x, y), (x+w, y+h), (255, 0, 0), 2)

    cv2.imshow('oxxostudio', img)
    if cv2.waitKey(1) == ord('q'):
        break     # 按下 q 鍵停止
cap.release()